# Generated by Django 3.0.6 on 2020-07-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='person_name',
            field=models.CharField(default='None', max_length=64),
        ),
    ]
