# Generated by Django 3.0.6 on 2020-07-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bids_person_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='category',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='listings',
            name='listed_by',
            field=models.CharField(default='admin', max_length=64),
        ),
    ]
